apiVersion: v1
kind: Service
metadata:
  name: sip-calculator-service
spec:
  selector:
    app: sip-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort