apiVersion: v1
kind: Service
metadata:
  name: kubernetes-ci-cd-pipeline-main
spec:
  selector:
    app: kubernetes-ci-cd-pipeline-main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort